theme:
  name: material
  palette:
    primary: custom
  features:
    - content.code.copy
    - navigation.footer
    - header.autohide
site_url: 'https://qbicsoftware.github.io/research-data-management/'
site_name:  Life Science Data Management
repo_url: https://github.com/qbicsoftware/research-data-management
repo_name: qbicsoftware/research-data-management
nav:
  - What's new: index.md
  - Get started:
      Process Overview: get_started/process_overview.md
  - Batch: batch/sample-batch.md
  - Developers & Stewards:
      - API: developers/api.md
      - Metadata Concepts: metadata/concepts.md
  - Experiment:
      - Introduction: experiment/experiment_introduction.md
      - Creation: experiment/experiment_creation.md
      - Confounding Variables: experiment/confounding-variables.md
  - Measurement:
      - Introduction: measurement/measurement_introduction.md
      - Editing: measurement/measurement_edit.md
      - Registration: measurement/measurement_registration.md
  - Ontology:
      - Introduction: ontology_search/ontology_search_introduction.md
  - Project:
      - Introduction: project/project_introduction.md
      - Access Management: project/project_access.md
      - Editing: project/project_edit.md
      - Registration: project/project_registration.md
  - Raw data:
      - Download Data: rawdata/raw_data_download.md
      - Upload Data: rawdata/raw_data_upload.md
  - User:
      - Editing: user/user_edit.md
      - Password Reset: user/password_reset.md
      - Registration: user/user_registration.md
extra_css:
  - stylesheets/extra.css
extra:
  version:
    provider: mike
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qbicsoftware/research-data-management
      name: research-data-management on Github
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
